# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080


# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: myapp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API docs


# 钉钉机器人配置
dingtalk:
  robot:
    webhook-url: https://oapi.dingtalk.com/robot/send?access_token=66ee36d70ab36d9f124e0329a0987786c16e2fe2618eeaa968f373cf9191c7ab
    secret: SECa083f7bde05dc44365be2243e21f46808ac2d4ea5f00b7a3dbbd5ed712595a2c

# 日志配置
logging:
  level:
    root: INFO
    org.start.app: DEBUG
    org.start.app.filter: INFO
  file:
    name: ./logs/myapp.log

